### ISSUE TITLE
Question for you about the steal pokemon script

### ISSUE THREAD

**Issue by kolbdog3333** [ellabrella/pokeemerald#1]
Is there a way so the Pokemon that you steal can be added to the Pokedex?

**Comment by ellabrella** [comment]
hi there,

it's possible to add this functionality but i'm not planning on doing so myself.

there is a function called "GetSetPokedexFlag" - in the pokedex.h file i think - which takes two arguments.  you can call it like "GetSetPokedexFlag(stolenMonSpecies, FLAG_SET_CAUGHT)" somewhere relevant in the code.  i would recommend trying to insert it into cmd_givecaughtpokemon to start with.  not sure 100% how you would get the stolen mon's species, i assume there's some way to access that via gBattleMons stuff.

i don't recommend trying to figure this out unless you're a programmer or you have the help of one & i'm not able to help out any more than this at the moment.

thank you for your interest!
